






(https://wesbos.com/javascript/04-the-dom/built-in-and-custom-data-attributes)
    1.  [Data Attributes](https://wesbos.com/javascript/04-the-dom/built-in-and-custom-data-attributes/#data-attributes)
-   [Creating HTML<span class="videoNumber">Part 25</span>](https://wesbos.com/javascript/04-the-dom/creating-html)
    1.  [append method](https://wesbos.com/javascript/04-the-dom/creating-html/#append-method)
    2.  [insertAdjacentElement method](https://wesbos.com/javascript/04-the-dom/creating-html/#insertadjacentelement-method)
    3.  [Generating An Unordered List](https://wesbos.com/javascript/04-the-dom/creating-html/#generating-an-unordered-list)
-   [HTML from Strings and XSS<span class="videoNumber">Part 26</span>](https://wesbos.com/javascript/04-the-dom/html-from-strings-and-xss)
    1.  [document.createRange() and document.createFragment()](https://wesbos.com/javascript/04-the-dom/html-from-strings-and-xss/#documentcreaterange-and-documentcreatefragment)
    2.  [Security and Santization](https://wesbos.com/javascript/04-the-dom/html-from-strings-and-xss/#security-and-santization)
    3.  [XSS (Cross Site Scripting)](https://wesbos.com/javascript/04-the-dom/html-from-strings-and-xss/#xss-cross-site-scripting)
-   [Traversing and Removing Nodes<span class="videoNumber">Part 27</span>](https://wesbos.com/javascript/04-the-dom/traversing-and-removing-nodes)
    1.  [The difference between an Node and an Element](https://wesbos.com/javascript/04-the-dom/traversing-and-removing-nodes/#the-difference-between-an-node-and-an-element)
    2.  [Properties to work with Nodes and Elements](https://wesbos.com/javascript/04-the-dom/traversing-and-removing-nodes/#properties-to-work-with-nodes-and-elements)
    3.  [Removing Elements](https://wesbos.com/javascript/04-the-dom/traversing-and-removing-nodes/#removing-elements)
-   [Cardio<span class="videoNumber">Part 28</span>](https://wesbos.com/javascript/04-the-dom/cardio)
    1.  [closest method](https://wesbos.com/javascript/04-the-dom/cardio/#closest-method)




##### <span class="grit">Module 12 - Advanced Flow Control</span>

-   <a href="https://wesbos.com/javascript/12-advanced-flow-control/66-the-event-loop-and-callback-hell" class="currentModule">The Event Loop and Callback Hell<span class="videoNumber">Part 66</span></a>
-   <a href="https://wesbos.com/javascript/12-advanced-flow-control/67-promises" class="currentModule">Promises<span class="videoNumber">Part 67</span></a>
    1.  <a href="https://wesbos.com/javascript/12-advanced-flow-control/67-promises/#then-method" class="currentModule">.then() method</a>
    2.  <a href="https://wesbos.com/javascript/12-advanced-flow-control/67-promises/#promiseall" class="currentModule">Promise.all()</a>
    3.  <a href="https://wesbos.com/javascript/12-advanced-flow-control/67-promises/#promiserace" class="currentModule">Promise.race()</a>
-   <a href="https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling" class="currentModule currentPage currentSection">Promises - Error Handling<span class="videoNumber">Part 68</span></a>
    1.  <a href="https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling/#promiseallsettled" class="currentModule currentPage">Promise.allSettled()</a>
-   <a href="https://wesbos.com/javascript/12-advanced-flow-control/69-refactoring-callback-hell-to-promise-land" class="currentModule">Refactoring Callback Hell to Promise Land<span class="videoNumber">Part 69</span></a>
-   <a href="https://wesbos.com/javascript/12-advanced-flow-control/70-async-await" class="currentModule">Async/Await<span class="videoNumber">Part 70</span></a>
-   <a href="https://wesbos.com/javascript/12-advanced-flow-control/71-async-await-error-handling" class="currentModule">Async/Await Error Handling<span class="videoNumber">Part 71</span></a>
    1.  <a href="https://wesbos.com/javascript/12-advanced-flow-control/71-async-await-error-handling/#handling-errors-with-higher-order-functions" class="currentModule">Handling Errors with Higher Order Functions</a>
-   <a href="https://wesbos.com/javascript/12-advanced-flow-control/72-async-await-prompt-ui" class="currentModule">Async/Await Prompt UI<span class="videoNumber">Part 72</span></a>
    1.  <a href="https://wesbos.com/javascript/12-advanced-flow-control/72-async-await-prompt-ui/#running-an-event-listener-only-once" class="currentModule">Running an Event Listener Only Once</a>
-   <a href="https://wesbos.com/javascript/12-advanced-flow-control/73-async-typer-ui-two-ways" class="currentModule">Async Typer UI - Two Ways<span class="videoNumber">Part 73</span></a>

##### <span class="grit">Module 13 - Ajax and Fetching Data</span>

-   [AJAX and APIs<span class="videoNumber">Part 74</span>](https://wesbos.com/javascript/13-ajax-and-fetching-data/74-ajax-and-apis)
    1.  [What is an API?](https://wesbos.com/javascript/13-ajax-and-fetching-data/74-ajax-and-apis/#what-is-an-api)
    2.  [JSON](https://wesbos.com/javascript/13-ajax-and-fetching-data/74-ajax-and-apis/#json)
    3.  [AJAX](https://wesbos.com/javascript/13-ajax-and-fetching-data/74-ajax-and-apis/#ajax)
    4.  [Public API list](https://wesbos.com/javascript/13-ajax-and-fetching-data/74-ajax-and-apis/#public-api-list)
-   [CORS and Recipes<span class="videoNumber">Part 75</span>](https://wesbos.com/javascript/13-ajax-and-fetching-data/75-cors-and-recipes)
    1.  [Query Parameters](https://wesbos.com/javascript/13-ajax-and-fetching-data/75-cors-and-recipes/#query-parameters)
    2.  [CORS](https://wesbos.com/javascript/13-ajax-and-fetching-data/75-cors-and-recipes/#cors)
        -   [What is CORS?](https://wesbos.com/javascript/13-ajax-and-fetching-data/75-cors-and-recipes/#what-is-cors)
        -   [CORS policy](https://wesbos.com/javascript/13-ajax-and-fetching-data/75-cors-and-recipes/#cors-policy)
    3.  [Babel](https://wesbos.com/javascript/13-ajax-and-fetching-data/75-cors-and-recipes/#babel)
    4.  [Browserlist](https://wesbos.com/javascript/13-ajax-and-fetching-data/75-cors-and-recipes/#browserlist)
    5.  [Proxy](https://wesbos.com/javascript/13-ajax-and-fetching-data/75-cors-and-recipes/#proxy)
-   [Dad Jokes<span class="videoNumber">Part 76</span>](https://wesbos.com/javascript/13-ajax-and-fetching-data/76-dad-jokes)
    1.  [Headers](https://wesbos.com/javascript/13-ajax-and-fetching-data/76-dad-jokes/#headers)
    2.  [Getting a Random Index](https://wesbos.com/javascript/13-ajax-and-fetching-data/76-dad-jokes/#getting-a-random-index)
    3.  [Loading State & CSS Loader](https://wesbos.com/javascript/13-ajax-and-fetching-data/76-dad-jokes/#loading-state--css-loader)
-   [Currency Converter<span class="videoNumber">Part 77</span>](https://wesbos.com/javascript/13-ajax-and-fetching-data/77-currency-converter)
    1.  [Caching the Rates](https://wesbos.com/javascript/13-ajax-and-fetching-data/77-currency-converter/#caching-the-rates)
    2.  [Converting](https://wesbos.com/javascript/13-ajax-and-fetching-data/77-currency-converter/#converting)
    3.  [Hooking Up The UI](https://wesbos.com/javascript/13-ajax-and-fetching-data/77-currency-converter/#hooking-up-the-ui)
        -   [Input Event on a Form](https://wesbos.com/javascript/13-ajax-and-fetching-data/77-currency-converter/#input-event-on-a-form)
        -   [Wiring up Handlers](https://wesbos.com/javascript/13-ajax-and-fetching-data/77-currency-converter/#wiring-up-handlers)
        -   [Formatting Currency using Number Format API](https://wesbos.com/javascript/13-ajax-and-fetching-data/77-currency-converter/#formatting-currency-using-number-format-api)

##### <span class="grit">Module 14 - ES Modules and Structuring Larger Apps</span>
##### <span class="grit">Module 15 - Final Round of Exercises</span>


<span class="grit">Promises - Error Handling</span>
===================================================


JavaScript, Promises, Error HandlingEdit Post

In this lesson we will talk about the opposite of resolving, which is rejecting.

When a promise goes awry, and you want to bail on it, you can call the reject function.

Let's go back to our `makePizza` definition and inside of our promise we need to check whether one of the toppings chosen for the pizza is pineapple.

If it is true, we need to reject the pizza from happening.

For now will only check for lowercase "pineapple" but we will have to try to weed out people who uppercase it as well later. If that condition is met, then we will call reject and pass it "seriously? get out".

To do that we will add the code below.

    if (toppings.includes('pineapple')) {
      reject("Seriously? Get out 🍍");
    }

Now let's go to the bottom of the script section and comment out the code we added in the previous lesson when we were doing an example on how to run promises concurrently.

Below that commented out code add the following 👇

    makePizza(['cheese','pineapple']).then(pizza => {
      console.log(pizza);
    })

<span class="gatsby-resp-image-wrapper" style="position:relative;display:block;margin-left:auto;margin-right:auto;max-width:1500px"> <span class="gatsby-resp-image-background-image" style="padding-bottom:65.06666666666668%;position:relative;bottom:0;left:0;background-image:url(https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling/'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAANCAIAAAAmMtkJAAAACXBIWXMAAAsTAAALEwEAmpwYAAACPUlEQVQoz2OYceDu5N03erZc7NhwtmPD2ZZ1Z+fsvXLm1hPvxDxuTWtRY3dhI1cRIxdRIxchAydBPXsE0ndgYIhdxRC3miF+DUPCWhCKX8OYvI4zZ7OQfZyArh2/aQC/WSC/WTCfeaiAia+AibegsZegkYeAiY+goRsDQ8p6huR1UJSyjiF5LUPSOoaEdVxW0UJ69vxmQfym/vxmwfymQQKmfgIWoQIWYSCGsbegoTtD26ZznVsutm++0LLxQvP6s33bL/dsOt+z7ZJJYCq3po2gibeAkaeAsReINPIQMPIG2WnkIWjgLGDkwfDj4e0/j+78e/Ho/+tn/z++/v7q+fvH93+/fhKWkseqZiVs4iFg6C5g5AnW4AoiQcgTwmD49f7jr1evf75+8+vjh78/f/76+u3nl6//f/2KyCxmVbMSMvUVMA0QMPUHIRN/ARM/EMPYR8AsSMAsiOE/Bvj3D0SGZ5awqlkLmfmClBp7g5CRJyjMoAw/ARMfBpBaiHK4ZjAZllHMpmopbOIlYOgGRiD3Cxo4Cxp6CBq6CRq5Cxp5YrMZTIamwzQbewoYeYFDyxPseTdBAxcIwqeZVc1a2BTivWABUFSB/WziC7YWr80gP6taCRh68Rl48Ol78Bt4COi5COjaC+g58us6Cug5COg74tacVcalaa1o7yZn5SJt6yFu6Slm5S5u6yVp5ipn5SZl5SNm4obb2RklXLpu0s7B4vZ+svZBEnZhQhZ+QpZ+wua+IpZ+whb+QuZ+AM/OY1YS7EKwAAAAAElFTkSuQmCC');background-size:cover;display:block"></span> <img src="https://wesbos.com/static/ccae6012cd92aa343781ffdf7158843b/aa440/1037.png" title="promise rejection error - uncaught in promise" alt="promise rejection error - uncaught in promise" class="gatsby-resp-image-image" /> </span>

What does that log "Uncaught (in promise)" mean?

It means that there was an error in one of our promises, but we did not write any code in order to handle that error and try to catch it.

The way you catch an error in a promise is you chain a `.catch()` to it.

Catch will pass you the error as a parameter which we will use to log the error as shown bel;ow.

    makePizza(['cheese','pineapple'])
      .then(pizza => {
        console.log(pizza);
      })
      .catch(err => {
        console.log('Oh noooo!!');
        console.log(err);
      })

As you see, we no longer get an error logged because we caught and logged the error ourselves.

<span class="gatsby-resp-image-wrapper" style="position:relative;display:block;margin-left:auto;margin-right:auto;max-width:736px"> <span class="gatsby-resp-image-background-image" style="padding-bottom:15.466666666666667%;position:relative;bottom:0;left:0;background-image:url(https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling/'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAADCAYAAACTWi8uAAAACXBIWXMAAAsTAAALEwEAmpwYAAAApElEQVQI1yWOi2rDMBRD8/+fmLVeEj+aG+fRuLVdD5Yz7AmEEEhC3bZteL+yriv7vpNzbkwpkXMipcw7RmKMhBAQEWSeMU64TcLX8GAWad2YEt3zeWKsRRuD955PKcT4ppRPG/4pCa5fKqofhm/6vkepO9bq5rXWHMfRMl14BaxzjXV08f5flwU3C1bfkIdp4fpymiaUUozj2I5Udc5xnifXdfEH0pDiLmAew9IAAAAASUVORK5CYII=');background-size:cover;display:block"></span> <img src="https://wesbos.com/static/511011a2ff46698112001223d0140969/f941f/1038.png" title="catching the uncaught promise error and logged in console" alt="catching the uncaught promise error and logged in console" class="gatsby-resp-image-image" /> </span>

`.then()` will only run when the promise resolves successfully, and the catch will only run if the promise doesn't go successfully.

Almost always with your promise built functions you must chain a `.then()` and a `.catch()` at the end so that if anything goes wrong, you are able to catch it and display it to the user.

What Wes will usually do is make a function called `handleError` which will take in the error and log it like so 👇

    function handleError(err) {
      console.log('Oh noooo!');
      console.log(err);
    }

Now instead of catching the error using the code we had before we can simply replace it as shown below 👇

    makePizza(['cheese', 'pineapple'])
      .then(pizza => {
        console.log(pizza);
      })
      .catch(handleError);

In the code above we are passing the reference to the function which will then handle the error.

It's important to note that not every single promise needs a catch on the end.

Go back to our pizzas where we chained a bunch of promises together and modify the pizza with no toppings to instead pass the topping of "pineapple",

<span class="gatsby-resp-image-wrapper" style="position:relative;display:block;margin-left:auto;margin-right:auto;max-width:1500px"> <span class="gatsby-resp-image-background-image" style="padding-bottom:49.86666666666667%;position:relative;bottom:0;left:0;background-image:url(https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling/'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAKCAIAAAA7N+mxAAAACXBIWXMAAAsTAAALEwEAmpwYAAABuUlEQVQoz2NYc/zahjP3N56+t+zgtdXH7vimlfJpWQkZuQkauggZuAjoOwrpOwoZOAkZOAnqOyIjESMXBoaUDQyJaxjiV4HIlA2ctgmierbS5q4S5t6ilt4iRi4Ceg5o2uCIYcLW81N2XJ6048rErRem7b5uE5nDo2ElZ+WkauOiYuclae4ubOwobOSEXfOX96+/f3z7/+fXD29e/vz8PiG/kk3FQtrCVdbMVc7CU8zUTcjQScgQh+Znz5/fuXv32ZPHz1++/vTpY1xBNZuquYyFs6Kls5KVh4S5m7CJk7Cxo4iJkwjIfgdkxPDxwYMP9+5+fvb03Yvnvz59jMutYFO3lrH2VLD2VLDxk7DwEjZ1FTJ2EzR2A4WikSsyYvj/7x8I/f//D0zGF1SzqdvK2nor2ngr2fpL2PiIWHgKGnsKGHkIGnsIQBCMzfAfBiCa4wqqWJXNpMyd5a0cFazcxE1dhAwdhY2QkLGjiLGTCCgUHTE1V7Mqm8vYuCk5ucvZuknYuIqaOYuaO4uau4gYuwgaOAkaOApCgtDACYtmNhVzcQsPMTMXSVBQOwsaOAqBEUgbJJz1oKENAJg91xYlFbIoAAAAAElFTkSuQmCC');background-size:cover;display:block"></span> <img src="https://wesbos.com/static/f385cec54528ce724c65ead03816368e/aa440/1040.png" title="not every promise needs a catch statement at the end" alt="not every promise needs a catch statement at the end" class="gatsby-resp-image-image" /> </span>

What happens there is we go through the chain of promises and then as soon as we hit the code where we try to make a pizza with a pineapple we get the "uncaught in promise" error.

<span class="gatsby-resp-image-wrapper" style="position:relative;display:block;margin-left:auto;margin-right:auto;max-width:738px"> <span class="gatsby-resp-image-background-image" style="padding-bottom:24.53333333333333%;position:relative;bottom:0;left:0;background-image:url(https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling/'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAFCAYAAABFA8wzAAAACXBIWXMAAAsTAAALEwEAmpwYAAABIElEQVQY0y2OyU7DMABE8/8/xCI4sEpwQCyN43Sxq9RO3Cy2kwZo2R4i4vA00ow0M8leSrzWjIs5PpdEkRG15rXYMGpFyDL8S8p7VfERAkNZstUau1hQa403hma9pi9LPoMn+cgy1OkJw/kZ4/ERr5cXHJ4eGW+uOdzfsbu9on+45ds5iIG9q6hyiRGCSkrcfD5pp1Z8NjUJQ09crXBZhhMpg1KU6Yy4WtLkc0ohiLaAIULooPewizD2sPvnL4uBH9+R4Dt21rKRkrUQlIslRuaT12o90RcFg6kIpsZvtkSzxW8cbeFo1hWHuubHt3x3LQnBM1qDzSVFmqJfZjRK8dU20yp9z35boVKFeDakz4Y8tSwzSz4zyJnlzdXT+7/CXywDcFZXqDtiAAAAAElFTkSuQmCC');background-size:cover;display:block"></span> <img src="https://wesbos.com/static/a7c18494d53b0529a17d7a6cab7b35fd/774b6/1041.png" title="in chain of promises - error uncaught promise" alt="in chain of promises - error uncaught promise" class="gatsby-resp-image-image" /> </span>

So how do we catch the error?

Does it mean we have to add a `catch` after each `then`? That would be annoying. Thankfully, the answer is no.

You just need to put one catch at the very end that will be able to handle our error.

<span class="gatsby-resp-image-wrapper" style="position:relative;display:block;margin-left:auto;margin-right:auto;max-width:1500px"> <span class="gatsby-resp-image-background-image" style="padding-bottom:48.266666666666666%;position:relative;bottom:0;left:0;background-image:url(https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling/'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAKCAIAAAA7N+mxAAAACXBIWXMAAAsTAAALEwEAmpwYAAABp0lEQVQoz32PTUsCQRiA99CHR2dn1chWqbRDlO3OfrVroDPjoBGLnbpXEP2PbkbnThF0KCqiCOxUv6BD125FSaVYgZpUhhtrBWEfw3N45/DwPi/Hze1x83vc7C63kO+0l4QRi5cZRGkvygCZgTH8DxxbPqG5E5Y7tldP0eIKGI73GngomY6SbH8iCyXCy5iX/pCrj+XGc71cLL7Wa+ubO90R3a/QoIZDGuk1GFSIT6O8REDsN7lQKNyXbkvFu6dqZWP3wBM1ejQatlKDZka0pgSV8ojwiECFQJm0y2fnF1eFm8vrm0qtvra978oqDZmpsJHuG58UUCsbEegOP+Srcv2x9lx6qFRfmms7h56o7lepaNEBk4nWpE+n7sIY/qRNdlqv8fbmOM7WQb47orey2aCZCcWnBNTKlj/AQMJuiEyARHgJc82m03ScRsOVN/fzHf2qX02JFglP0OAE8xkpqBBBo1Cl7tkKcYcPFNq2+cgT0QMqDSbT4TgLjDNBxRAlBQULCgaxpHc0Ab7Rnt01ZAasrJjIhvBMT3zaq9vA+EK33e8XXt1+B9doyNaApzdYAAAAAElFTkSuQmCC');background-size:cover;display:block"></span> <img src="https://wesbos.com/static/10c0a364fe27c5d82fdf70605382622a/aa440/1042.png" title="handling the error in chanin of promises in code" alt="handling the error in chanin of promises in code" class="gatsby-resp-image-image" /> </span>

The thing about an error happening in a promise chain is that where the error happens, it will then bail out of executing the rest of the promise chain.

If you have 7 or 8 steps in the promise chain and they are all dependent on one another, then that is good because if step 3 in the breaks, you don't want to continue to step 4.

But sometimes you want to continue even if one of the promises fails. If that is the case, then promise chaining is not what you want to use. Instead, you'd want to use some of the other Promise static methods like `Promise.all()` or `Promise.race()`.

Let's do an example. We will start with 2 pizzas.

    const p1 = makePizza(['pep']);
    const p2 = makePizza(['pineapple']);

<span class="grit"><a href="#promiseallsettled" class="hash-anchor before"></a>Promise.allSettled()</span>
----------------------------------------------------------------------------------------------------------

We will use a new API that we haven't learned yet called `Promise.allSettled()`.

Let's start by making a mega promise.

    const dinnerPromise2 = Promise.allSettled([p1, p2]);

Let's just get the results and log them for now.

    dinnerPromise2
      .then(results => {
        console.log(results);
      })

<span class="gatsby-resp-image-wrapper" style="position:relative;display:block;margin-left:auto;margin-right:auto;max-width:1500px"> <span class="gatsby-resp-image-background-image" style="padding-bottom:42.66666666666667%;position:relative;bottom:0;left:0;background-image:url(https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling/'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAJCAIAAAC9o5sfAAAACXBIWXMAAAsTAAALEwEAmpwYAAABCklEQVQoz4WR2VLDMAxF8/+/SEib0pnGa2x5qa3INjidAi0DnGddaXTucJxnIaV3kK+RiLYdRCSi8gRRa817P47j6zRxwQfOuTYr4zJ68CGCAwuwGpMwt9bqI621EOPxOM+nkxBisNKCttFYdK4StVJqLa2WSlvZtvaDUkrqZEQcor06AStbDOfoPTqL3meAZEwCe7v2G0OA4I03nMV1rftnf40/hUE4ddbi/LZeLnSN2zW0do/X+l9Yg7NBKWlXlXHLGfeXEiLeNzxARCnnlDvdtlJaSwFaKqUXtiyMMcYFF36ndIVftmOMh6575pwPXbqU1hrEdJP5rdfOZ7KU0qsK4WUcp8P0UdU7o8kJs5a1S7EAAAAASUVORK5CYII=');background-size:cover;display:block"></span> <img src="https://wesbos.com/static/0156a185fb3da4f655f47730225c7789/aa440/1043.png" title="output of promise as first one fulfilled, second one rejected using Promise.allSettled()" alt="output of promise as first one fulfilled, second one rejected using Promise.allSettled()" class="gatsby-resp-image-image" /> </span>

As you can see in our results we can see that the first one was **fulfilled** and the second one was **rejected**. Fulfilled is another word they use for resolved.

If we tried that example but with `Promise.all()` like so, you will see that the code will break.

    const dinnerPromise2 = Promise.all([p1, p2]);

<span class="gatsby-resp-image-wrapper" style="position:relative;display:block;margin-left:auto;margin-right:auto;max-width:1500px"> <span class="gatsby-resp-image-background-image" style="padding-bottom:11.200000000000001%;position:relative;bottom:0;left:0;background-image:url(https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling/'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAACCAIAAADXZGvcAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAX0lEQVQI11XC7Q5AIBQAUO//iKxb6XYjH5nkyhrmlzk71YBW1qIjP1IXw7qFuM5xCRunI/O7HLnk78msATQAGVNNLZIwVjlqlJPWCjQCW8C59zfvN/P1X1JyWpGUA+IDmKJvji3xonIAAAAASUVORK5CYII=');background-size:cover;display:block"></span> <img src="https://wesbos.com/static/4a61807517fb33370c5eef5e86f6d7ea/aa440/1044.png" title="Promise.all() produces error in console if one of the promise is rejected" alt="Promise.all() produces error in console if one of the promise is rejected" class="gatsby-resp-image-image" /> </span>

That is because `Promise.all` assumes that all of them will go successfully.

If you want to catch any errors that happen in `Promise.all()` you would have to catch them like so 👇

    const dinnerPromise2 = Promise.all([p1, p2]).catch(handleError);

<span class="gatsby-resp-image-wrapper" style="position:relative;display:block;margin-left:auto;margin-right:auto;max-width:1500px"> <span class="gatsby-resp-image-background-image" style="padding-bottom:25.866666666666667%;position:relative;bottom:0;left:0;background-image:url(https://wesbos.com/javascript/12-advanced-flow-control/68-promises-error-handling/'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAFCAIAAADKYVtkAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAsklEQVQY01XM0bKCMAxFUf7/Iy0R2kpbgSlJk6Ygd3R0rq45r/t0y7pY5+Z5LoVEuKmyKIoSvydVVbW+pq1RKc55a21KqUPEHiCleyHadz1/PD77JyJ935uLiTF2ROS9X9YVt1wwM0t5IaLjOJ4HX87zZGYAuBgTQug2xBCj97d7DMkPU4gA12Ech2HMOTNza+07FhEAMMZM0/SMrXUhRsStSlFVZq61yse+7z8xv+MQ4h+Zjh2vQL28+QAAAABJRU5ErkJggg==');background-size:cover;display:block"></span> <img src="https://wesbos.com/static/562148ef5c743a05570f96263c646040/aa440/1045.png" title="using catch handler with Promise.all()" alt="using catch handler with Promise.all()" class="gatsby-resp-image-image" /> </span>

That is probably not what you want because if one of them breaks, you might still want the other one, because those other pizzas are still good.

`Promise.allSettled()` will tell you when all the promises are done, regardless of whether they were rejected or resolved.

There are a few more error handling techniques that we need to use but they do not get introduced until we learn **async/await**.

Let's go back and refactor the last exercise we did to use promises instead of callback hell.

Find an issue with this post? Think you could clarify, update or add something?

All my posts are available to edit on Github. Any fix, little or small, is appreciated!

[Edit on Github](https://github.com/wesbos/wesbos/tree/master/src/javascript/12-advanced-flow-control/68-promises-error-handling/68-promises-error-handling.mdx)

[**← Prev**](https://wesbos.com/javascript/12-advanced-flow-control/67-promises/)

Promises

[**Next →**](https://wesbos.com/javascript/12-advanced-flow-control/69-refactoring-callback-hell-to-promise-land/)

Refactoring Callback Hell to Promise Land

### <span class="highlight">Syntax Podcast</span>

Hold on — I'm grabbin' the last one.
